/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NanoDevice_CONSTANTS_H
#define NanoDevice_CONSTANTS_H

#include "NanoDevice_types.h"

namespace EyelockNano {

class NanoDeviceConstants {
 public:
  NanoDeviceConstants();

};

extern const NanoDeviceConstants g_NanoDevice_constants;

} // namespace

#endif
