# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\psoc\chamonix\fixed_boot\boot.cydsn\boot.cyprj
# Date: Thu, 01 Nov 2018 15:04:07 GMT
#set_units -time ns
create_clock -name {EZI2C_CAM_SCBCLK(FFB)} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {EZI2C_CAM_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 2 3} [list]


# Component constraints for C:\psoc\chamonix\fixed_boot\boot.cydsn\TopDesign\TopDesign.cysch
# Project: C:\psoc\chamonix\fixed_boot\boot.cydsn\boot.cyprj
# Date: Thu, 01 Nov 2018 15:04:05 GMT
