/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NanoDevice_constants.h"

namespace EyelockNano {

const NanoDeviceConstants g_NanoDevice_constants;

NanoDeviceConstants::NanoDeviceConstants() {
}

} // namespace

