/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "IDAC_1.h"
#include "RESIST.h"
#include "RESIST_aliases.h"
#include "Opamp_FACE.h"
#include "VFB.h"
#include "VFB_aliases.h"
#include "ADC.h"
#include "PWM.h"
#include "PWM_aliases.h"
#include "Clock_1.h"
#include "isr_TIMER.h"
#include "Clock_2.h"
#include "TIMER.h"
#include "PWM_CHARGE.h"
#include "EN_A.h"
#include "EN_A_aliases.h"
#include "EN_B.h"
#include "EN_B_aliases.h"
#include "VREF_A.h"
#include "VREF_A_aliases.h"
#include "Opamp_1.h"
#include "VREF_B.h"
#include "VREF_B_aliases.h"
#include "Opamp_2.h"
#include "TRIG_LEFT.h"
#include "TRIG_LEFT_aliases.h"
#include "TRIG_FACE.h"
#include "TRIG_FACE_aliases.h"
#include "TRIG_RIGHT.h"
#include "TRIG_RIGHT_aliases.h"
#include "isr_bbi2c.h"
#include "Control_Trig.h"
#include "IDAC_2.h"
#include "EN_C.h"
#include "EN_C_aliases.h"
#include "VREF_C.h"
#include "VREF_C_aliases.h"
#include "EZI2C.h"
#include "EZI2C_PINS.h"
#include "EZI2C_PVT.h"
#include "EZI2C_EZI2C.h"
#include "EZI2C_EZI2C_PVT.h"
#include "EZI2C_BOOT.h"
#include "Comp_1.h"
#include "MAX_I.h"
#include "MAX_I_aliases.h"
#include "IFB.h"
#include "IFB_aliases.h"
#include "Bootloadable_1.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "EZI2C_SCBCLK.h"
#include "EZI2C_sda.h"
#include "EZI2C_sda_aliases.h"
#include "EZI2C_scl.h"
#include "EZI2C_scl_aliases.h"
#include "EZI2C_SCB_IRQ.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

