# config.make generated by configure script
POCO_CONFIG = NXT
POCO_BASE = /home/builder/ws_nanoNXT/linux/pkg/poco-1.7.2-all
POCO_BUILD = /home/builder/ws_nanoNXT/linux/pkg/poco-1.7.2-all
POCO_FLAGS = 
POCO_PREFIX = /usr/local
OMIT = Data/ODBC Data/MySQL MongoDB PDF CppParser
LINKMODE = STATIC
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_FLAGS
export POCO_PREFIX
export LINKMODE
