#ifndef _GRI_EYESEGMENTATION_LIBRARY_DEF_
#define _GRI_EYESEGMENTATION_LIBRARY_DEF_

#ifdef EYESEGMENTATIONLIB_EXPORTS
#undef  EYESEGMENTATIONLIB_EXPORTS_DLL_EXPORT
#define EYESEGMENTATIONLIB_EXPORTS_DLL_EXPORT __declspec( dllexport )
#else // EYESEGMENTATIONLIB_EXPORTS
#define EYESEGMENTATIONLIB_EXPORTS_DLL_EXPORT
#endif

#endif // _GRI_EYESEGMENTATION_LIBRARY_DEF_
