#ifndef _MAMIGO_BASE_IMAGE_PROCESSING_LIBRARY_DEF_
#define _MAMIGO_BASE_IMAGE_PROCESSING_LIBRARY_DEF_

#ifdef MAMIGOBASEIPL_EXPORTS
#undef  MAMIGO_BASE_IPL_DLL_EXPORT
#define MAMIGO_BASE_IPL_DLL_EXPORT __declspec( dllexport )
#else // MAMIGOBASEIPL_EXPORTS
#define MAMIGO_BASE_IPL_DLL_EXPORT
#endif

#endif // _MAMIGO_BASE_IMAGE_PROCESSING_LIBRARY_DEF_
