/*
 * IrisMacros.h
 *
 *  Created on: Oct 31, 2014
 *      Author: developer
 */

#ifndef IRISMACROS_H_
#define IRISMACROS_H_

#define IRIS_SIZE 1280
#define GUID_SIZE 36
#define IRIS_SIZE_INCLUDING_MASK (IRIS_SIZE*2)
#define IRIS_SIZE_INCLUDING_MASK_PER_PERSON (IRIS_SIZE_INCLUDING_MASK*2)
#define IRIS_SIZE_INCLUDING_MASK_AND_GUID_PER_PERSON (IRIS_SIZE_INCLUDING_MASK_PER_PERSON+GUID_SIZE)

#define COMPRESS_IRIS_SIZE (IRIS_SIZE>>1)
#define COMPRESS_IRIS_SIZE_INCLUDING_MASK (COMPRESS_IRIS_SIZE*2)
#define COMPRESS_IRIS_SIZE_INCLUDING_MASK_PER_PERSON (COMPRESS_IRIS_SIZE_INCLUDING_MASK*2)
#define COMPRESS_IRIS_SIZE_INCLUDING_MASK_AND_GUID_PER_PERSON (COMPRESS_IRIS_SIZE_INCLUDING_MASK_PER_PERSON+GUID_SIZE)

#define COARSE_IRIS_SIZE (IRIS_SIZE>>2)
#define COARSE_IRIS_SIZE_INCLUDING_MASK (COARSE_IRIS_SIZE*2)
#define COARSE_IRIS_SIZE_INCLUDING_MASK_PER_PERSON (COARSE_IRIS_SIZE_INCLUDING_MASK*2)

#define UPDATEPERSON 0
#define DELETEPERSON 1


#endif /* IRISMACROS_H_ */
