#!/bin/sh

EYELOCK_APP_NAME="Eyelock"
EYELOCK_USER="eyelock"
EYELOCK_HOME_PATH="/home/$EYELOCK_USER"

    if [ -e "$EYELOCK_HOME_PATH/Eyelock.lock" ] ; then
	    rm -rf "$EYELOCK_HOME_PATH/Eyelock.lock"
    else
	    echo "No $EYELOCK_HOME_PATH/Eyelock.lock exist"
    fi

    touch /var/run/eyelock.pid
    echo > /home/eyelock/Eyelock.run
    chown eyelock:eyelock /var/run/eyelock.pid
    echo "starting the eyelock as services before login as eyelock from terminal ..."

    /sbin/start-stop-daemon --start --make-pidfile --pidfile /var/run/eyelock.pid --retry 10 --chuid eyelock -v --exec "/home/eyelock/Eyelock" -- 

